baseURL: "https://vittoriofaraco.com/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Vittorio Faraco
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Work
                  url: work
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Newsletter
                  url: https://vittoriofaraco.substack.com/

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Vittorio Faraco"
    author: Vittorio Faraco
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: Vittorio Faraco
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Vittorio Faraco"
        Content: >
            I am a freelance AI and data consultant, MSc Computer Engineering student and AI researcher.

            I am a MSc student in Computer Engineering at Politecnico di Bari, in Italy.

            <br><br>My main interest is AI: I am working specifically on Recommender Systems algorithms, on trustworthy ML/DL problems such as Fairness, on promising methods, tools and areas such as Optimization, Causality, Reinforcement Learning, Conversational AI and Synthetic Data Generation. One of my goals is to study and expand the intersection between these technologies and Healthcare solutions.

            <br><br>Besides that, I am also working as a freelance AI, data and web consultant and I am sharing thoughts and lessons related to my work and interests online, mainly on YouTube.

    socialIcons:
        - name: github
          url: "https://github.com/vtfrc"
        - name: youtube
          url: "https://youtube.com/@VittorioFaraco2"
        - name: linkedin
          url: "https://linkedin.com/in/vittoriofaraco"
        - name: twitter
          url: "https://twitter.com/vittoriofaraco"

    editPost:
        URL: "https://github.com/vtfrc/vittoriofaraco/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true